name: Go

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go clean
        apt install -y python3
        python3 -m pip install Flask

    - name: Build
      run: go build -v .
    
    - name: Test
      run: |
        cd example
        python server_example.py &
        sleep 2
        cd ../
        go test -v
